my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: JGRBCAD-UXB25055

      # User/password auth
      user: JACKHUGHE
      password: "{{ env_var('SNOWFLAKE_PWD') }}"

      database: PRJCT
      warehouse: COMPUTE_WH
      schema: TGT
      client_session_keep_alive: False

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None